services:
  oracle-db:
    image: container-registry.oracle.com/database/free:latest-lite
    container_name: oracle-db-free
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PWD=MyLocalPassword123
