CREATE TABLE morros (
    morro_id VARCHAR2(36) PRIMARY KEY,
    nome VARCHAR2(255) NOT NULL,
    latitude FLOAT NOT NULL,
    longitude FLOAT NOT NULL
);

-- Nova tabela para representar versões das caixas
CREATE TABLE versoes_caixa (
    versao_id VARCHAR2(36) PRIMARY KEY,
    nome VARCHAR2(50) NOT NULL, -- Nome ou identificador da versão
    tipo_caixa VARCHAR2(50) NOT NULL -- Tipo da caixa (ex.: sensor, alerta)
);

CREATE TABLE caixas (
    caixa_id VARCHAR2(36) PRIMARY KEY,
    tipo VARCHAR2(50) NOT NULL, -- Ex.: sensor, alerta
    versao_id VARCHAR2(36) NOT NULL, -- Referência para a versão
    morro_id VARCHAR2(36) NOT NULL,
    latitude FLOAT NOT NULL,
    longitude FLOAT NOT NULL,
    ativo NUMBER(1) DEFAULT 1,
    codigo_patrimonio VARCHAR2(50) UNIQUE NOT NULL,
    CONSTRAINT fk_morro FOREIGN KEY (morro_id) REFERENCES morros(morro_id),
    CONSTRAINT fk_versao FOREIGN KEY (versao_id) REFERENCES versoes_caixa(versao_id)
);

CREATE TABLE tipo_metricas (
    tipo_metrica_id VARCHAR2(36) PRIMARY KEY,
    nome VARCHAR2(255) NOT NULL,
    unidade VARCHAR2(50) NOT NULL
);

-- Associar métricas às versões de caixa
CREATE TABLE versao_metricas (
    versao_id VARCHAR2(36) NOT NULL,
    tipo_metrica_id VARCHAR2(36) NOT NULL,
    CONSTRAINT fk_versao_metrica FOREIGN KEY (versao_id) REFERENCES versoes_caixa(versao_id),
    CONSTRAINT fk_metrica FOREIGN KEY (tipo_metrica_id) REFERENCES tipo_metricas(tipo_metrica_id),
    PRIMARY KEY (versao_id, tipo_metrica_id)
);

CREATE TABLE leituras (
    leitura_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    caixa_id VARCHAR2(36) NOT NULL,
    tipo_metrica_id VARCHAR2(36) NOT NULL,
    valor FLOAT NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_caixa FOREIGN KEY (caixa_id) REFERENCES caixas(caixa_id),
    CONSTRAINT fk_metrica_leitura FOREIGN KEY (tipo_metrica_id) REFERENCES tipo_metricas(tipo_metrica_id)
);

CREATE TABLE alerta (
    alerta_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    morro_id VARCHAR2(36) NOT NULL,
    caixa_id VARCHAR2(36) NOT NULL,
    status VARCHAR2(50) NOT NULL,
    data_inicio TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data_final TIMESTAMP,
    CONSTRAINT fk_alerta_morro FOREIGN KEY (morro_id) REFERENCES morros(morro_id),
    CONSTRAINT fk_alerta_caixa FOREIGN KEY (caixa_id) REFERENCES caixas(caixa_id)
);